version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend/
    # command: "uvicorn app.api.main:app --reload --workers 1 --host 0.0.0.0 --port ${PORT}"
    ports:
      - 8000:8000
